#!/bin/env bash

# Input IP
read -p "Please input the IP: " ip
ip="${ip#"${ip%%[![:space:]]*}"}"  # Trim leading whitespace
ip="${ip%"${ip##*[![:space:]]}"}"  # Trim trailing whitespace

# Input user (optional)
read -p "Input user, leave blank if none: " user
user="${user#"${user%%[![:space:]]*}"}"
user="${user%"${ip##*[![:space:]]}"}"

if [[ -z "$user" ]]; then
    connection="$ip"
else
    connection="$user@$ip"
fi
connection_nick=$connection
# Private key path (optional)
read -p "Does it need a private key to unlock? (y/n): " answer
answer="${answer,,}"  # Convert to lowercase
conncetionFile=$answer
if [[ $answer == "y" ]]; then
    read -p "Please input the whole path to the key: " key
    key="${key#"${key%%[![:space:]]*}"}"
    key="${key%"${ip##*[![:space:]]}"}"
    connectionFile=" $connection -o $key "
    connection="-i $key $connection"
fi

# Nickname (optional)
read -p "Do you want to give it a nickname? (y/n): " answer
answer="${answer,,}"

if [[ $answer == "y" ]]; then
    read -p "Please input the nickname (one word only): " nick
    nick="${nick#"${nick%%[![:space:]]*}"}"
    nick="${nick%"${ip##*[![:space:]]}"}"
    connection="$connection $nick"
else
    connection=$connection_nick
    connectionFile="$connectionFile $connection_nick"
fi


# Append to the config file
echo "$connection" >> ~/.local/bin/scripts/.saved_ssh_conf
echo "$connectionFile" >> ~/.local/bin/scripts/.saved_sshfs_conf


