#!/usr/bin/env python3

print("Please input the ip:")
ip = input()
ip = ip.strip()
print("Input user, leave blank if none")
user = input()
user = user.strip()
connection = None
if user == None or user == "":
        connection = ip
else:
    connection=user+"@"+ip
print("does it need a private key to unlock? (y/n)")
answer = input()
answer = answer.strip()
if answer.lower() == "n":
    pass
else:
    print("please input the whole path to the key")
    key = input()
    key = key.strip()
    connection = "-i "+ key+" "+connection

file = open("./.saved_ssh_conf", "a")
file.write(connection)


