#!/usr/bin/env bash

file=~/.local/bin/scripts/.saved_ssh_conf
if [[ $# -eq 1 ]]; then
    selected=$1
    file2=~/.local/bin/scripts/.saved_sshfs_conf
    if [ $selected == "add-connection" ]; then
       ~/.local/bin/scripts/save
    fi
     if [ $selected == "encrypt" ]; then
         touch $file
    ansible-vault encrypt $file
    ansible-vault encrypt $file2
    fi
      if [ $selected == "decrypt" ]; then
    ansible-vault decrypt $file
    ansible-vault decrypt $file2
    fi
      if [ $selected == "fs" ]; then
    selected=$(cat $file2 |awk '{print $NF}'| fzf)
    selected=$(cat $file2 | fzf --query=$selected --select-1 )
    selected=$(echo "$selected" | awk '{ $NF=""; print }')
    sshfs $selected
    fi
    exit 0
else
    selected=$(cat $file |awk '{print $NF}'| fzf)
    selected=$(cat $file | fzf --query=$selected --select-1 )
    selected=$(echo "$selected" | awk '{ $NF=""; print }')
    ssh $selected
fi

if [[ -z $selected ]]; then
    exit 0
fi
